include: package:flutter_lints/flutter.yaml
analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - prefer_single_quotes
    - unawaited_futures
    - sort_child_properties_last
    - prefer_final_locals
    - unnecessary_null_checks
    - avoid_redundant_argument_values
    - avoid_returning_null_for_future
    - no_logic_in_create_state
    - constant_identifier_names
